### ISSUE TITLE
Fail to create a JIRA issue with {{

### ISSUE THREAD

**Issue by machadoit** [atlassian/gajira-create#8]
Hey guys,

We are using your gajira-create with the GitHub issue body, but it seems that if the body has '{{' in the text the request fail. Do you have any suggestions on how can we make it work?

Error on the action:
https://github.com/codacy/helm-ssm/runs/1111647834?check_suite_focus=true

Issue triggering that error:
https://github.com/codacy/helm-ssm/issues/26

Usage of gajira-create filling the description field:
https://github.com/codacy/helm-ssm/blob/master/.github/workflows/create_issue.yml#L35

Thanks!

**Comment by rudzon** [comment]
@machadoit Hi! 
It should now work with new release ( https://github.com/atlassian/gajira-create/releases/tag/v2.0.1 )
Please check for your scenario. Feel free to create another issue in case of troubles
